# Virtual Machine Configuration
os: linux
dist: xenial

# Project JDK
language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "susolopolis"
    token:
      secure: "6f08c48e26cdedfabf95fc4664dfa7c52a54e099" # encrypted value of your token
install:
    bash <(curl -s -L http://bit.ly/install-sonar-scanner)

after_success:
    sonar-scanner
