# This will run on Travis' 'new' container-based infrastructure
sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      
 deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

script:
  - doxygen Doxyfile

