# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
 branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: P7_Laboratorio
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/susolopolis/P7_Laboratorio.git

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
    
script:
  - make
  
after_success:
 - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentation.sh
  - ./generateDocumentation.sh
    
    
