# Virtual Machine Configuration
os: linux
dist: xenial

# Project JDK
language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "susolopolis"
    token:
      secure: "SONAR_TOKEN" # encrypted value of your token
install:
    bash <(curl -s -L http://bit.ly/install-sonar-scanner)
    
    apt:
        -doxygen

after_success:
    -doxygen Doxyfile
    
    
